### ISSUE TITLE
Can't install as shard

### ISSUE THREAD

**Issue by denisgolius** [veelenga/emoji.cr#14]
What I'm doing wrong?

```
❯ shards install shard.yml 
Error in shard.yml: missing required attribute: name at line 5, column 1

  3.     github: veelenga/emoji.cr
  4.     branch: master
     ^
```

```
ls -1
bin
LICENSE
main.cr
README.md
shard.yml
```

**Comment by veelenga** [comment]
Is this a correct command? Shouldn't it be just `shards install` ?

**Comment by veelenga** [comment]
Oh, i believe you need to add missing fields to your `shard.yml`. See example here: https://github.com/veelenga/vicr/blob/master/shard.yml

**Comment by denisgolius** [comment]
> Oh, i believe you need to add missing fields to **your** `shard.yml`. See example here: https://github.com/veelenga/vicr/blob/master/shard.yml

Fixed it, thanks!
